#!/bin/bash
set -eu

if (( $# != 1 )); then
	echo "usage: $0 DATADIR" >/dev/stderr
	exit 1
fi

DATADIR="$1"

# In case bootcounter.service is installed, read its counter file:
if [ -e /var/lib/bootcounter.count ]; then
	BOOTNUM="$(cat /var/lib/bootcounter.count)"
	OUTPREFIX="$DATADIR/$BOOTNUM-"
else
	OUTPREFIX="$DATADIR/"
fi

N=1
while [[ -e "$OUTPREFIX$N" ]]; do
	N=$(( N + 1 ))
done

OUTDIR="$OUTPREFIX$N"

function archive() {
	SIZE=$(stat --format='%s' "$1")
	if (( SIZE < 1048576 )); then
		cp "$1" "$2"
	elif [ -e /usr/bin/pigz ]; then
		/usr/bin/pigz -c "$1" > "$2.gz"
	else
		gzip -c "$1" > "$2.gz"
	fi
}

mkdir "$OUTDIR"
cd "$OUTDIR"

set +e

dmesg > dmesg
dmidecode > dmidecode
cp -r /sys/firmware/acpi/tables tables
archive /var/log/kern.log kern.log
archive /var/log/syslog syslog
